
name: Build Static Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build static site
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: static-website-files
        path: dist/
        retention-days: 30
        
    - name: Create downloadable zip
      run: |
        cd dist
        zip -r ../static-website-complete.zip .
        cd ..
        
    - name: Upload complete zip
      uses: actions/upload-artifact@v4
      with:
        name: website-complete-zip
        path: static-website-complete.zip
        retention-days: 30
